name: Unit tests

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  test-node:
    name: Test on Node.js v${{ matrix.node-version }} and Jest v${{ matrix.jest-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 19.x, 20.x]
        jest-version: [29]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install with jest v${{ matrix.jest-version }}
        run: |
          npm install --dev jest@${{ matrix.jest-version }} babel-jest@${{ matrix.jest-version }}
          npm install --no-audit
          npm rebuild
      - name: run tests
        run: npm run test
  test-os:
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: install
        run: |
          npm install --no-audit
          npm rebuild
      - name: run tests
        run: npm run test
